
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[361] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   70,   68,
        5,    1,    1,   26,    4,   53,   24,   68,   21,   30,
       12,   28,   13,   23,   68,   14,   54,   54,   32,   20,
       11,   17,   53,   53,   22,   31,   36,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   18,   68,   29,   67,   65,   65,
       67,   59,   57,   57,   56,   58,   64,   62,   62,   60,
       63,    5,    1,   25,   53,   53,   10,   52,   33,    6,
        0,    2,    3,    6,    0,    0,    0,   54,    0,   34,
       19,   15,   16,   35,   53,   53,   53,   53,   53,   53,

       53,   53,   53,   53,   53,   53,   53,   53,   53,   52,
       53,   53,   53,   53,   53,   53,   53,   53,   43,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   27,   65,
       66,   57,   58,   55,   62,   63,   61,    6,    0,    0,
        0,    3,    6,    0,    7,    0,   54,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       52,   53,   53,   53,   37,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,

       53,   53,   53,   53,   53,   53,    0,    6,    6,    0,
        6,    0,    7,    0,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   42,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   52,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,    8,   50,   53,   53,    6,    0,    0,    6,    7,
       53,   53,   53,   53,   53,   53,   39,   53,   53,   53,
       53,    9,   52,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   52,   53,   53,
       51,    6,    0,   53,   49,   52,   53,   53,   53,   53,

       41,   53,   53,   53,   53,   53,   53,   53,   53,   46,
       47,   48,   53,   53,   53,   53,   40,   52,    0,   53,
       38,   53,   53,   53,   53,   53,   53,   53,   53,   53,
        0,    0,   53,   53,   53,   53,   53,   53,    0,    0,
       53,   53,   53,    0,    0,   53,    0,    0,   53,    0,
        0,    0,    0,    0,    0,    0,    0,   45,   44,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,    7,    7,    7,    7,   24,    7,
        7,    7,   25,    7,    7,    7,    7,    7,    7,    7,
        7,    7,   26,    7,    7,    7,    7,    7,    7,    7,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,    7,   41,   42,   43,   44,
       45,   46,    7,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    2,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    1,
        1,    1,    1,    3,    3,    3,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[369] =
    {   0,
        0,    0,   56,   58,   60,   68,   72,   76,  358, 1115,
      341, 1115,  328,  295, 1115,   65, 1115,  300, 1115, 1115,
     1115,  292, 1115,   50,   67,   75,   75,   79, 1115,   68,
      278,   79,   89,   94, 1115, 1115, 1115,   98,  101,  105,
      112,  117,  103,  123,  119,  142,  121,  151,  156,  153,
      158,  172,  175,  107, 1115,  215, 1115, 1115, 1115,  264,
      243, 1115, 1115,  251, 1115,  186, 1115, 1115,  246, 1115,
      190,  238, 1115, 1115,  109,    0, 1115, 1115, 1115,  207,
      200, 1115,    0,  180,  226,  233,  210,  237,  240, 1115,
     1115, 1115, 1115, 1115,  245,  162,  247,  251,  256,  258,

      260,  262,  265,  267,  270,  272,  278,  203,  274,  280,
      284,  294,  296,  304,  306,  302,  308,  310,  315,  317,
      319,  321,  323,  330,  333,  335,  338,  343,  352,  355,
      361,  366,  369,  371,  373,  378,  376,  384, 1115, 1115,
     1115, 1115, 1115, 1115, 1115, 1115, 1115,  403,  418,  380,
      188,    0,  411,  386,  388,  422,  432,  407,  426,  436,
      441,  443,  446,  451,  457,  459,  461,  464,  470,  474,
      483,  487,  490,  492,  494,  496,  498,  500,  505,  508,
      510,  514,  523,  525,  527,  531,  533,  535,  537,  539,
      542,  552,  548,  557,  561,  563,  565,  567,  574,  569,

      577,  581,  587,  593,  595,  600,  602,  612,  614,  186,
      616,  618,  635,  637,  639,  641,  643,  645,  651,  653,
      655,  662,  657,  664,  668,  672,  675,  681,  684,  688,
      691,  693,  696,  700,  702,  707,  711,  717,  719,  721,
      725,  727,  730,  737,  739,  741,  745,  747,  750,  752,
      754,  764,  766,  769,  772,  775,  778,  168,  781,  792,
      795,  797,  801,  806,  803,  808,  810,  814,  818,  823,
      827,  829,  831,  835,  837,  845,  847,  849,  852,  856,
      858,  861,  863,  869,  875,  878,  880,  882,  891,  893,
      895,  897,  176,  900,  902,  907,  916,  918,  920,  922,

      924,  926,  930,  933,  938,  935,  940,  942,  945,  947,
      961,  963,  967,  969,  971,  973, 1115,  977,  168,  979,
      981,  983,  987,  990,  993,  998, 1002, 1005, 1011, 1014,
      159,  152, 1017, 1019, 1021, 1023, 1025, 1027,  168,  146,
     1033, 1035, 1041,  137,  166, 1043,  130,  127, 1049,  131,
      111,  107,   78,   70,   61,   32,   28, 1115, 1115, 1115,
     1096, 1099, 1102,   66, 1105, 1108,   64, 1111
    } ;

static const flex_int16_t yy_def[369] =
    {   0,
      360,    1,  361,  361,  362,  362,  363,  363,  360,  360,
      360,  360,  360,  360,  360,  364,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  364,  364,  360,  360,  360,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  365,  360,  360,  360,  360,
      366,  360,  360,  360,  364,  367,  360,  360,  360,  360,
      360,  360,  368,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  364,  364,  364,  367,  364,  364,

      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  368,  360,  360,  360,  360,  360,  364,  364,  364,
      367,  367,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,

      364,  364,  364,  364,  364,  364,  360,  360,  360,  360,
      360,  360,  360,  360,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  360,  360,  360,  360,  360,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  360,  360,  364,  364,  364,  364,  364,  364,  364,

      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  360,  364,  360,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      360,  360,  364,  364,  364,  364,  364,  364,  360,  360,
      364,  364,  364,  360,  360,  364,  360,  360,  364,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,    0,
      360,  360,  360,  360,  360,  360,  360,  360
    } ;

static const flex_int16_t yy_nxt[1174] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   16,   33,   34,   35,   10,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   16,   46,
       16,   47,   16,   48,   16,   49,   50,   51,   52,   16,
       53,   54,   16,   16,   16,   55,   56,   57,   59,   60,
       59,   60,   63,   64,   78,   65,   76,   61,   75,   61,
       63,   64,   79,   65,   68,   69,  359,   70,   68,   69,
      358,   70,   76,   76,   80,   80,   82,   66,   90,   91,
       84,   83,   85,   85,   84,   66,   88,   88,   86,   71,

       93,   94,   86,   71,  357,   87,   76,   76,   81,   89,
       86,   76,   76,  356,   86,   76,   98,  355,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   99,   76,
       76,  354,   95,  100,   76,   76,   76,   76,   76,   76,
       76,   76,   96,  105,  111,  138,  112,   97,  101,  102,
      106,  103,  109,  107,  114,  113,  108,  353,  104,   76,
       76,  110,  115,  118,  116,  122,  352,  117,   76,   76,
       76,   76,  351,   76,   76,   76,   76,  350,  119,   76,
       76,  348,  123,  347,  120,  121,  124,  126,  129,   76,
       76,  144,   76,   76,  345,  147,  130,  153,  153,  344,

      125,  340,  127,  149,  339,  128,  131,  132,  159,  133,
      135,  134,  332,  144,  317,  149,  293,  147,  136,  137,
       76,   76,  144,  258,  148,  148,  147,  156,  156,  144,
      149,  210,  144,  147,  144,  151,  147,  150,  147,   72,
       87,   84,  149,   85,   85,  154,  172,  154,  145,   86,
      155,  155,   84,  142,   88,   88,   87,  157,  157,  141,
       86,   86,   76,   76,   76,   76,  140,   89,  161,  161,
       89,  139,   86,   76,   98,   76,   76,   76,   76,   76,
       76,  162,   76,   76,   76,   76,   99,   76,   76,   76,
       76,   76,   76,  158,  160,   76,   76,   76,   76,   92,

      166,   76,   76,  170,   78,  163,  165,  164,   77,  171,
      173,   76,   76,   76,   76,  167,   74,  168,  169,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,  174,
       73,  175,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   72,  176,  177,  178,  180,   76,   76,  179,
       76,   76,   76,   76,  181,   76,   76,  360,  182,  360,
       76,   76,  183,  360,  186,  360,  184,  185,  189,   76,
       76,  187,   76,   76,  188,  192,  360,  190,   76,   76,
      360,  181,  191,   76,   76,  360,   76,   76,   76,   76,
       76,   76,  195,   76,   76,   76,   76,  209,  209,  194,

      193,   76,   76,  155,  155,  213,  213,  196,  198,  202,
      150,  197,  200,  360,  199,  204,  360,  205,  214,  201,
      148,  148,  360,  206,   76,   76,  149,  203,  211,  211,
      207,  181,  207,  150,  149,  208,  208,   84,  149,  156,
      156,  212,  215,   76,   76,   86,  149,   84,  360,  157,
      157,  360,   87,   76,   76,   86,  360,   86,  161,  161,
      161,  161,   89,   76,   76,  216,  360,   86,   76,   76,
      360,  162,  360,  162,   76,   76,   76,   76,   76,   76,
      360,   76,   76,  360,  217,  360,  219,   76,   76,  360,
      221,   76,   76,  360,  218,  360,  181,  360,  220,  181,

       76,   76,  360,  222,   76,   76,  360,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,  360,
      181,  226,   76,   76,  227,   76,   76,   76,   76,  228,
      223,   76,   76,  229,  224,  225,  231,  360,  181,  232,
       76,   76,   76,   76,   76,   76,  360,  230,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,  181,   76,
       76,  360,  236,  360,  233,   76,   76,  234,  181,   76,
       76,  360,  237,  235,   76,   76,  238,  239,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,  360,  240,
      241,   76,   76,  242,   76,   76,  360,  243,   76,   76,

      247,  360,  246,  244,   76,   76,  360,  249,  360,  245,
       76,   76,   76,   76,  360,  248,  181,   76,   76,  208,
      208,  250,  252,  360,  251,  360,  254,  253,  360,  256,
      256,  209,  209,  211,  211,  259,  259,  149,  360,  149,
      360,  255,  257,  360,  150,  360,  212,  360,  212,  149,
      360,  149,  213,  213,  260,  260,   76,   76,   76,   76,
       76,   76,   76,   76,  360,  214,  360,  214,   76,   76,
       76,   76,   76,   76,   76,   76,  261,  360,  263,   76,
       76,   76,   76,  360,  262,   76,   76,  360,  266,   76,
       76,  264,   76,   76,  360,  181,  360,  265,   76,   76,

      181,   76,   76,  360,  267,   76,   76,  268,   76,   76,
       76,   76,  181,   76,   76,  360,  270,   76,   76,   76,
       76,  269,  360,  272,   76,   76,  360,  271,   76,   76,
      360,  274,  273,  276,   76,   76,   76,   76,   76,   76,
      360,  181,   76,   76,   76,   76,  275,   76,   76,  360,
      279,  360,  280,  277,   76,   76,   76,   76,   76,   76,
      281,  278,   76,   76,   76,   76,  282,   76,   76,   76,
       76,   76,   76,  360,  285,  360,  283,  360,  284,  360,
      286,   76,   76,   76,   76,  181,   76,   76,  287,   76,
       76,  181,  256,  256,  360,  292,  292,  360,  211,  211,

      360,  289,  360,  288,  149,  257,  360,  291,  257,  260,
      260,  212,   76,   76,   76,   76,  149,  290,   76,   76,
       76,   76,  214,   76,   76,   76,   76,   76,   76,  360,
      294,   76,   76,  360,  295,   76,   76,  297,  360,  298,
       76,   76,  360,  296,   76,   76,   76,   76,   76,   76,
      360,  181,   76,   76,   76,   76,  360,  299,  301,  300,
      360,  302,   76,   76,   76,   76,   76,   76,  360,   76,
       76,  360,  303,   76,   76,   76,   76,  304,   76,   76,
       76,   76,  360,  306,  181,  181,   76,   76,  305,  307,
      360,  309,   76,   76,  310,   76,   76,   76,   76,   76,

       76,  360,  312,  360,  308,  360,  311,  360,   76,   76,
       76,   76,   76,   76,  292,  292,  181,   76,   76,   76,
       76,  360,  319,  313,   76,   76,  314,  257,  360,  181,
      315,  360,  316,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,  360,  318,   76,   76,  320,
       76,   76,   76,   76,  360,   76,   76,   76,   76,   76,
       76,  321,   76,   76,   76,   76,  325,  360,  323,  322,
      181,  324,  360,  181,  360,  181,  360,  181,   76,   76,
       76,   76,  360,  181,   76,   76,   76,   76,   76,   76,
       76,   76,  331,  326,   76,   76,   76,   76,   76,   76,

       76,   76,  360,  327,   76,   76,  329,   76,   76,  360,
       76,   76,  360,  328,  330,   76,   76,  360,  181,   76,
       76,  360,   76,   76,  360,  334,  335,  181,   76,   76,
      333,   76,   76,  336,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,  360,  181,  337,  181,
       76,   76,   76,   76,  338,  360,  181,  181,   76,   76,
       76,   76,  360,  342,  343,  341,   76,   76,  360,  360,
      360,  181,  360,  360,  360,  181,  360,  360,  349,  360,
      181,  360,  360,  181,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  346,   58,   58,   58,   62,

       62,   62,   67,   67,   67,  143,  360,  143,  146,  360,
      146,  152,  360,  152,    9,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360
    } ;

static const flex_int16_t yy_chk[1174] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        4,    4,    5,    5,   24,    5,  367,    3,  364,    4,
        6,    6,   24,    6,    7,    7,  357,    7,    8,    8,
      356,    8,   16,   16,   25,   25,   26,    5,   30,   30,
       27,   26,   27,   27,   28,    6,   28,   28,   27,    7,

       32,   32,   28,    8,  355,   27,   33,   33,   25,   28,
       27,   34,   34,  354,   28,   38,   38,  353,   39,   39,
       43,   43,   40,   40,   54,   54,   75,   75,   38,   41,
       41,  352,   33,   39,   42,   42,   45,   45,   47,   47,
       44,   44,   34,   41,   43,   54,   43,   34,   39,   40,
       41,   40,   42,   41,   44,   43,   41,  351,   40,   46,
       46,   42,   44,   45,   44,   47,  350,   44,   48,   48,
       50,   50,  348,   49,   49,   51,   51,  347,   46,   96,
       96,  345,   48,  344,   46,   46,   48,   49,   50,   52,
       52,   66,   53,   53,  340,   71,   51,   84,   84,  339,

       48,  332,   49,   84,  331,   49,   51,   51,   96,   51,
       52,   51,  319,   66,  293,   84,  258,   71,   52,   53,
      108,  108,   66,  210,   80,   80,   71,   87,   87,   66,
       80,  151,   66,   71,   66,   81,   71,   80,   71,   72,
       87,   85,   80,   85,   85,   86,  108,   86,   69,   85,
       86,   86,   88,   64,   88,   88,   85,   89,   89,   61,
       88,   85,   95,   95,   97,   97,   60,   88,   98,   98,
       89,   56,   88,   99,   99,  100,  100,  101,  101,  102,
      102,   98,  103,  103,  104,  104,   99,  105,  105,  106,
      106,  109,  109,   95,   97,  107,  107,  110,  110,   31,

      103,  111,  111,  106,   22,  100,  102,  101,   18,  107,
      109,  112,  112,  113,  113,  104,   14,  105,  105,  116,
      116,  114,  114,  115,  115,  117,  117,  118,  118,  110,
       13,  111,  119,  119,  120,  120,  121,  121,  122,  122,
      123,  123,   11,  112,  113,  114,  116,  124,  124,  115,
      125,  125,  126,  126,  117,  127,  127,    9,  118,    0,
      128,  128,  120,    0,  122,    0,  121,  121,  126,  129,
      129,  123,  130,  130,  125,  128,    0,  127,  131,  131,
        0,  124,  127,  132,  132,    0,  133,  133,  134,  134,
      135,  135,  131,  137,  137,  136,  136,  150,  150,  130,

      129,  138,  138,  154,  154,  155,  155,  131,  133,  136,
      150,  132,  135,    0,  134,  137,    0,  137,  155,  135,
      148,  148,    0,  138,  158,  158,  148,  136,  153,  153,
      149,  136,  149,  148,  153,  149,  149,  156,  148,  156,
      156,  153,  158,  159,  159,  156,  153,  157,    0,  157,
      157,    0,  156,  160,  160,  157,    0,  156,  161,  161,
      162,  162,  157,  163,  163,  159,    0,  157,  164,  164,
        0,  161,    0,  162,  165,  165,  166,  166,  167,  167,
        0,  168,  168,    0,  160,    0,  164,  169,  169,    0,
      166,  170,  170,    0,  163,    0,  167,    0,  165,  168,

      171,  171,    0,  169,  172,  172,    0,  173,  173,  174,
      174,  175,  175,  176,  176,  177,  177,  178,  178,    0,
      170,  173,  179,  179,  174,  180,  180,  181,  181,  175,
      171,  182,  182,  177,  172,  172,  179,    0,  176,  180,
      183,  183,  184,  184,  185,  185,    0,  178,  186,  186,
      187,  187,  188,  188,  189,  189,  190,  190,  182,  191,
      191,    0,  185,    0,  183,  193,  193,  183,  186,  192,
      192,    0,  187,  184,  194,  194,  188,  189,  195,  195,
      196,  196,  197,  197,  198,  198,  200,  200,    0,  190,
      191,  199,  199,  192,  201,  201,    0,  193,  202,  202,

      197,    0,  196,  194,  203,  203,    0,  199,    0,  195,
      204,  204,  205,  205,    0,  198,  200,  206,  206,  207,
      207,  201,  203,    0,  202,    0,  205,  204,    0,  208,
      208,  209,  209,  211,  211,  212,  212,  209,    0,  211,
        0,  206,  208,    0,  209,    0,  211,    0,  212,  209,
        0,  211,  213,  213,  214,  214,  215,  215,  216,  216,
      217,  217,  218,  218,    0,  213,    0,  214,  219,  219,
      220,  220,  221,  221,  223,  223,  215,    0,  217,  222,
      222,  224,  224,    0,  216,  225,  225,    0,  220,  226,
      226,  218,  227,  227,    0,  221,    0,  219,  228,  228,

      222,  229,  229,    0,  223,  230,  230,  225,  231,  231,
      232,  232,  224,  233,  233,    0,  227,  234,  234,  235,
      235,  226,    0,  230,  236,  236,    0,  229,  237,  237,
        0,  233,  231,  235,  238,  238,  239,  239,  240,  240,
        0,  232,  241,  241,  242,  242,  234,  243,  243,    0,
      239,    0,  240,  236,  244,  244,  245,  245,  246,  246,
      241,  237,  247,  247,  248,  248,  242,  249,  249,  250,
      250,  251,  251,    0,  246,    0,  243,    0,  245,    0,
      248,  252,  252,  253,  253,  244,  254,  254,  249,  255,
      255,  247,  256,  256,    0,  257,  257,    0,  259,  259,

        0,  251,    0,  250,  259,  256,    0,  255,  257,  260,
      260,  259,  261,  261,  262,  262,  259,  254,  263,  263,
      265,  265,  260,  264,  264,  266,  266,  267,  267,    0,
      261,  268,  268,    0,  262,  269,  269,  264,    0,  266,
      270,  270,    0,  263,  271,  271,  272,  272,  273,  273,
        0,  265,  274,  274,  275,  275,    0,  268,  270,  269,
        0,  271,  276,  276,  277,  277,  278,  278,    0,  279,
      279,    0,  273,  280,  280,  281,  281,  274,  282,  282,
      283,  283,    0,  277,  278,  275,  284,  284,  276,  279,
        0,  281,  285,  285,  282,  286,  286,  287,  287,  288,

      288,    0,  284,    0,  280,    0,  283,    0,  289,  289,
      290,  290,  291,  291,  292,  292,  286,  294,  294,  295,
      295,    0,  296,  285,  296,  296,  287,  292,    0,  288,
      289,    0,  290,  297,  297,  298,  298,  299,  299,  300,
      300,  301,  301,  302,  302,    0,  294,  303,  303,  297,
      304,  304,  306,  306,    0,  305,  305,  307,  307,  308,
      308,  298,  309,  309,  310,  310,  306,    0,  304,  299,
      300,  305,    0,  302,    0,  307,    0,  308,  311,  311,
      312,  312,    0,  303,  313,  313,  314,  314,  315,  315,
      316,  316,  318,  309,  318,  318,  320,  320,  321,  321,

      322,  322,    0,  313,  323,  323,  315,  324,  324,    0,
      325,  325,    0,  314,  316,  326,  326,    0,  322,  327,
      327,    0,  328,  328,    0,  324,  325,  320,  329,  329,
      323,  330,  330,  326,  333,  333,  334,  334,  335,  335,
      336,  336,  337,  337,  338,  338,    0,  327,  328,  330,
      341,  341,  342,  342,  329,    0,  335,  336,  343,  343,
      346,  346,    0,  334,  337,  333,  349,  349,    0,    0,
        0,  342,    0,    0,    0,  338,    0,    0,  346,    0,
      341,    0,    0,  349,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  343,  361,  361,  361,  362,

      362,  362,  363,  363,  363,  365,    0,  365,  366,    0,
      366,  368,    0,  368,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
#line 819 "lex.yy.c"

#line 14 "jucompiler.l"
#include "y.tab.h"
#include "tree.h"
#include <string.h>
#include "semantics.h"   
int option = 0;
int yacc_option = 0;   
extern int line; 
int line_start = 1; 
extern int yacc_print;
extern int coluna;
int coluna_start = 1;
char STR1[32654];
int i = 0;
extern tnode* arvore;
extern table* tabela;
extern int second_phase;
int error = 0;
#line 839 "lex.yy.c"
#line 840 "lex.yy.c"

#define INITIAL 0
#define COMMENT1 1
#define STR 2
#define ERROR 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 34 "jucompiler.l"


#line 1063 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 361 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1115 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 36 "jucompiler.l"
{line++;coluna = 1;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "jucompiler.l"
{BEGIN (COMMENT1);line_start = line;coluna_start=coluna;coluna+=yyleng;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "jucompiler.l"
{coluna += yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "jucompiler.l"
{STR1[i] = '\"';i++;coluna_start = coluna;coluna+=yyleng;line_start = line;BEGIN (STR);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "jucompiler.l"
{coluna+=yyleng;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 43 "jucompiler.l"
{if(option) printf("REALLIT(%s)\n",yytext);coluna+=yyleng;yylval.str1=(char*)strdup(yytext);if(yacc_option) return REALLIT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 44 "jucompiler.l"
{if(option) printf("REALLIT(%s)\n",yytext);coluna+=yyleng;yylval.str1=(char*)strdup(yytext);if(yacc_option) return REALLIT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "jucompiler.l"
{if(option) printf("BOOLLIT(%s)\n",yytext);coluna+=yyleng;yylval.str1=(char*)strdup(yytext);if(yacc_option) return BOOLLIT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "jucompiler.l"
{if(option) printf("BOOLLIT(%s)\n",yytext);coluna+=yyleng;yylval.str1=(char*)strdup(yytext);if(yacc_option) return BOOLLIT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "jucompiler.l"
{if(option) printf("AND\n");coluna+=yyleng;return AND;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "jucompiler.l"
{if(option) printf("ASSIGN\n");coluna+=yyleng;if(yacc_option) return ASSIGN;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "jucompiler.l"
{if(option) printf("STAR\n");coluna+=yyleng;if(yacc_option) return STAR;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "jucompiler.l"
{if(option) printf("COMMA\n");coluna+=yyleng;if(yacc_option) return COMMA;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "jucompiler.l"
{if(option) printf("DIV\n");coluna+=yyleng;if(yacc_option) return DIV;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "jucompiler.l"
{if(option) printf("EQ\n");coluna+=yyleng;if(yacc_option) return EQ;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "jucompiler.l"
{if(option) printf("GE\n");coluna+=yyleng;if(yacc_option) return GE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "jucompiler.l"
{if(option) printf("GT\n");coluna+=yyleng;if(yacc_option) return GT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "jucompiler.l"
{if(option) printf("LBRACE\n");coluna+=yyleng;if(yacc_option) return LBRACE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "jucompiler.l"
{if(option) printf("LE\n");coluna+=yyleng;if(yacc_option) return LE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{if(option) printf("LT\n");coluna+=yyleng;if(yacc_option) return LT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "jucompiler.l"
{if(option) printf("LPAR\n");coluna+=yyleng;if(yacc_option) return LPAR;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "jucompiler.l"
{if(option) printf("LSQ\n");coluna+=yyleng;if(yacc_option) return LSQ;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "jucompiler.l"
{if(option) printf("MINUS\n");coluna+=yyleng;if(yacc_option) return MINUS;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{if(option) printf("MOD\n");coluna+=yyleng;if(yacc_option) return MOD;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "jucompiler.l"
{if(option) printf("NE\n");coluna+=yyleng;if(yacc_option) return NE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "jucompiler.l"
{if(option) printf("NOT\n");coluna+=yyleng;if(yacc_option) return NOT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "jucompiler.l"
{if(option) printf("OR\n");coluna+=yyleng;if(yacc_option) return OR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "jucompiler.l"
{if(option) printf("PLUS\n");coluna+=yyleng;if(yacc_option) return PLUS;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "jucompiler.l"
{if(option) printf("RBRACE\n");coluna+=yyleng;if(yacc_option) return RBRACE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{if(option) printf("RPAR\n");coluna+=yyleng;if(yacc_option) return RPAR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 72 "jucompiler.l"
{if(option) printf("RSQ\n");coluna+=yyleng;if(yacc_option) return RSQ;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 73 "jucompiler.l"
{if(option) printf("SEMICOLON\n");coluna+=yyleng;if(yacc_option) return SEMICOLON;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 74 "jucompiler.l"
{if(option) printf("ARROW\n");coluna+=yyleng;if(yacc_option) return ARROW;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 75 "jucompiler.l"
{if(option) printf("LSHIFT\n");coluna+=yyleng;if(yacc_option) return LSHIFT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 76 "jucompiler.l"
{if(option) printf("RSHIFT\n");coluna+=yyleng;if(yacc_option) return RSHIFT;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{if(option) printf("XOR\n");coluna+=yyleng;if(yacc_option) return XOR;} 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{if(option) printf("INT\n");coluna+=yyleng;if(yacc_option) return INT;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "jucompiler.l"
{if(option) printf("BOOL\n");coluna+=yyleng;if(yacc_option) return BOOL;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{if(option) printf("CLASS\n");coluna+=yyleng;if(yacc_option) return CLASS;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "jucompiler.l"
{if(option) printf("DOTLENGTH\n");coluna+=yyleng;if(yacc_option) return DOTLENGTH;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{if(option) printf("DOUBLE\n");coluna+=yyleng;if(yacc_option) return DOUBLE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "jucompiler.l"
{if(option) printf("ELSE\n");coluna+=yyleng;if(yacc_option) return ELSE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{if(option) printf("IF\n");coluna+=yyleng;if(yacc_option) return IF;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{if(option) printf("PRINT\n");coluna+=yyleng;if(yacc_option) return PRINT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{if(option) printf("PARSEINT\n");coluna+=yyleng;if(yacc_option) return PARSEINT;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{if(option) printf("PUBLIC\n");coluna+=yyleng;if(yacc_option) return PUBLIC;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{if(option) printf("RETURN\n");coluna+=yyleng;if(yacc_option) return RETURN;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{if(option) printf("STATIC\n");coluna+=yyleng;if(yacc_option) return STATIC;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 91 "jucompiler.l"
{if(option) printf("String\n");coluna+=yyleng;if(yacc_option) return STRING;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 92 "jucompiler.l"
{if(option) printf("VOID\n"); coluna+=yyleng;if(yacc_option) return VOID;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{if(option) printf("WHILE\n");coluna+=yyleng;if(yacc_option) return WHILE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 96 "jucompiler.l"
{if(option) printf("RESERVED(%s)\n" , yytext);coluna+=yyleng;if(yacc_option) return RESERVED;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{if(option) printf("ID(%s)\n",yytext);coluna+=yyleng;yylval.str1=(char*)strdup(yytext);if(yacc_option) return ID;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 98 "jucompiler.l"
{if(option) printf("INTLIT(%s)\n" , yytext);coluna+=yyleng;yylval.str1=(char*)strdup(yytext);if(yacc_option) return INTLIT;}
	YY_BREAK
case YY_STATE_EOF(STR):
#line 100 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n" , line_start,coluna_start);BEGIN 0;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 101 "jucompiler.l"
{STR1[i] = '\\';i++;STR1[i] = yytext[1];i++ ;coluna += yyleng;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 102 "jucompiler.l"
{if(option) printf("STRLIT(%s\")\n",STR1);i = 0;coluna+=yyleng;strcat(STR1,"\""); ;yytext = strdup(STR1);yyleng = strlen(STR1); yylval.str1 = strdup(STR1); memset(STR1,0,strlen(STR1));BEGIN 0; return STRLIT;}
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 103 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n" , line_start,coluna_start);coluna = 1 ;memset(STR1,0,strlen(STR1));i = 0; line++;BEGIN 0;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 104 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (%s)\n",line , coluna  ,yytext);coluna += yyleng;BEGIN ERROR;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 105 "jucompiler.l"
{STR1[i] = yytext[0];i++;coluna+=yyleng;}
	YY_BREAK
case YY_STATE_EOF(ERROR):
#line 108 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n" , line_start,coluna_start);memset(STR1,0,strlen(STR1));i = 0;coluna+=yyleng;BEGIN 0;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 109 "jucompiler.l"
{memset(STR1,0,strlen(STR1));i = 0;coluna+=yyleng;BEGIN 0;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 110 "jucompiler.l"
{coluna += yyleng;}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 111 "jucompiler.l"
{printf("Line %d, col %d: unterminated String literal\n" , line_start,coluna_start);coluna = 1; line++;memset(STR1,0,strlen(STR1));i = 0;BEGIN 0;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 112 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (%s)\n",line , coluna  ,yytext);coluna += yyleng;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 113 "jucompiler.l"
{coluna += yyleng;}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 116 "jucompiler.l"
{coluna = 1;line++;}
	YY_BREAK
case YY_STATE_EOF(COMMENT1):
#line 117 "jucompiler.l"
{BEGIN 0;printf("Line %d, col %d: unterminated comment\n" , line_start,coluna_start);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 118 "jucompiler.l"
{BEGIN 0;coluna+=yyleng;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 119 "jucompiler.l"
{coluna+=yyleng;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 121 "jucompiler.l"
{coluna += yyleng;return 0;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 122 "jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n" , line , coluna , yytext);coluna+=yyleng;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 124 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1485 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 361 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 361 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 360);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 124 "jucompiler.l"

int main(int argc, char *argv[])
{   
    if(argc == 2){
        if(!(strcmp(argv[1] , "-l"))){
            option = 1;
            yylex();
        }
        if(!(strcmp(argv[1] , "-t"))){
            yacc_print = 1;
            yacc_option = 1;
            yyparse();
            if(!error){
                printTree(arvore,0);
            }
        }
        if(!(strcmp(argv[1] , "-e2"))){
            yacc_option=1;
            yyparse();
        }
        if(!(strcmp(argv[1] , "-e1"))){
            yylex();
        }
        if(!(strcmp(argv[1], "-s"))){
            yacc_print = 1;
            yacc_option = 1;
            yyparse();
            //if(!error){
                check_program(arvore);
                show_table(tabela);
                printTree(arvore,0);
            //}
            
        }
    }
    else
        yyparse();
    
    return 0;
}

int yywrap()
{

return 1;

}
